### ISSUE TITLE
Missions en retard

### ISSUE THREAD

**Issue by mh0** [Wiiz83/ProjetAOC#12]
- Missions actuellement en retard : 
Mission de status EN_COURS, et dont la date de fin réelle à été mise à >dataDebut+durée
- Missions terminées en retard (archives, non gérés pour l'instant): 
Mission de status TERMINEE, et dont la date de fin réelle à été mise à >dataDebut+durée

== > 
Appeler mission.enRetard(), et afficher un JLablel pour signaler le retard si nécessaire

**Comment by Wiiz83** [comment]
Mettre en place une méthode pour mettre le statut EN_RETARD en TERMINEE.
Ex : missionEnCours.setStatut(Statut.TERMINEE)

**Comment by Wiiz83** [comment]
Et rajouter les missions en retard dans la JTable des alertes.
![image](https://cloud.githubusercontent.com/assets/10958435/25613981/718bd328-2f30-11e7-8593-5db872230d4f.png)

**Comment by Wiiz83** [comment]
Et changer le statut en terminée avec un mission.setStatut(Statut.TERMINEE) sur l'interface 
![image](https://cloud.githubusercontent.com/assets/10958435/25614534/9943232e-2f32-11e7-9482-be9f148f16d8.png)

**Comment by mh0** [comment]
Le statut "En retard" n'existe pas, et le statut d'une mission n'est pas persisté dans la bd mais déduit.
Le retard (avec sa durée, si jamais on a faire des analyses statistiques) se déduit de la fin date réelle.
A la création de la mission, la date de fin réelle est par défaut date_début+durée

**Comment by mh0** [comment]
Il faudrait donc rajouter le champs de date de fin réelle dans l'ihm pour correspondre au modèle

**Comment by Wiiz83** [comment]
Je pensais plutôt faire au clic d'un bouton "mission terminée", faire mission.setDateFin(datedujour), ça te vas ?

**Comment by Wiiz83** [comment]
Ouais non faut que l'utilisateur mette la date de fin c'est mieux. Un bouton ça va prendre la date du jour du coup c'est pas top
