### ISSUE TITLE
Création d'une nouvelle mission

### ISSUE THREAD

**Issue by Wiiz83** [Wiiz83/ProjetAOC#14]
Problème au niveau de l'ajout de compétence.
![image](https://cloud.githubusercontent.com/assets/10958435/25615062/6e5e8330-2f35-11e7-9851-35d64daedc51.png)

**Comment by mh0** [comment]
dateDebut est initialisée à null donc Mission :: cal.setTime(this.dateDebut) échoue.
On peut l'intialiser avec la date d’aujourd’hui (models.cal.today() )

**Comment by mh0** [comment]
Il faudrait faire pareil pour l'ihm donc (le champ date)

**Comment by mh0** [comment]
![image](https://cloud.githubusercontent.com/assets/17098140/25620981/5d6296d2-2f50-11e7-8753-849fe54b8c96.png)
