### ISSUE TITLE
 IHM - Duplication d'éléments

### ISSUE THREAD

**Issue by mh0** [Wiiz83/ProjetAOC#3]
DANS LE CAS D'UN NOUVEL ÉLÉMENT UNIQUEMENT : 
Dans Personnel et Missions, si je modifie 2 fois de suite les employés ou les compétences sans avoir enregistré, il y a duplication des éléments dans la liste Possession et Non Possession --> nécessaire de récupérer les éléments présents dans la JTable affiché pour récupérer ceux qui manquent à tout moment 
(Lucas).

**Comment by Wiiz83** [comment]
![image](https://cloud.githubusercontent.com/assets/10958435/25567987/4ffbc5d4-2df9-11e7-99fd-bba50b75d85c.png)
