### ISSUE TITLE
Missions Formation - IHM

### ISSUE THREAD

**Issue by mh0** [Wiiz83/ProjetAOC#7]

**Comment by Wiiz83** [comment]
Faut faire quoi exactement ? Je vois pas du tout ^^
C'est une mission comme une autre, donc rien a changé niveau IHM, non ?

**Comment by mh0** [comment]
La différence c'est qu'une formation a une liste de compétences , et pas de compétencesRequises, et qu'il n'y aura pas de notion de date de fin réelle / retard
Il faut une IHM séparée pour ça

**Comment by mh0** [comment]
![image](https://cloud.githubusercontent.com/assets/17098140/25616407/b03fb01a-2f3c-11e7-8704-e3f8d2a6b0fc.png)

**Comment by Wiiz83** [comment]
Je fais une page formation alors ? Comme ça on est tranquille
