### ISSUE TITLE
Missions formation - Automatisation de l'assignation de compétences à la fin de la formation

### ISSUE THREAD

**Issue by mh0** [Wiiz83/ProjetAOC#9]
Processus à lancer au démarrage de l'appli ? Avec un thread qui surveille l'état des formations ?

**Comment by Wiiz83** [comment]
Au démarrage de l'application uniquement, ça suffit je pense

**Comment by Wiiz83** [comment]
1. Lancement de l'assignation au lancement du programme donc soit dans Program.java soit ProgramFrame.java
2. Assignation si et seulement si la date de fin réelle est dépassée
